#!/bin/sh

# Number of processors +1
PROCESSORS="$(($(nproc)+1))"

# `-march=native` make binaries unportable
export CFLAGS='-march=native -O2 -pipe'
export CXXFLAGS="$CFLAGS"

# `--target-cpu=native` make binaries unportable
export RUSTFLAGS='-C opt-level=2 -C --target-cpu=native'

# make(1)
export MAKEFLAGS="-j$PROCESSORS -l$PROCESSORS"

unset -v PROCESSORS
