#!/bin/sh

export CFLAGS='-march=native -O3 -pipe' # Use '-O2' if compile fails (it's O not zero)
export CXXFLAGS="$CFLAGS"
export FCFLAGS="$CFLAGS"
export FFLAGS="$CFLAGS"
export RUSTFLAGS='-C opt-level=3 --target-cpu=native' # Use 'opt-level=2' if complie fails
export MAKEFLAGS="-j$(($(nproc)+1)) -l$(($(nproc)+1))"
