#!/usr/bin/env bash

## Prefered tool to exec as root
(( $UID == 0 )) || AUTH=doas

## My GitHub directories
GitHub="$HOME/GitHub/repositories"
GistHub="$HOME/GitHub/gists"

## Aliases
alias ghpcd="cd $GitHub"
alias gshcd="cd $GistHub"
alias cp='cp -vZ'
alias mv='mv -vZ'
alias rm='rm -v'
alias mkdir='mkdir -vZ'
alias rmdir='rmdir -v'
alias chown='chown -c'
alias chmod='chmod -c'
alias mount='mount -v'
alias umount='umount -v'
alias fstrim='fstrim -v'
alias ln='ln -v'
alias shred='shred -fv'
alias ls='ls -hFNX -T 0 --color=auto --group-directories-first --show-control-chars' # Minimal ls(1)
alias ip='ip -color=auto' # Colorful ip(1)
alias dmesg='dmesg --color=auto -H' # Colorful dmesg(1)
alias pcc="$AUTH pacman -Rnsc \$(pacman -Qtdq) && sync" # Remove orphans in Arch
alias grep='grep -sI --color=auto' # No errors when unreadable and colorful
alias fgrep='grep -F' # `grep -F` is a replacement for fgrep(1)
alias egrep='grep -E' # `grep -E` is a replacement for egrep(1)
alias diff='diff --color=auto --tabsize=4 ' # diff(1) with colors is a lots easier to read, also set tab size to 4
alias media="cd /media/$USER"
alias doas='doas ' # Required, if you want aliases to work with doas(1)
alias htop="htop -t -u $USER" # It's so much cleaner
alias xclip='xclip -selection clipboard' # Normal xclip(1) doesn't work for me
alias vol='pactl get-sink-volume @DEFAULT_SINK@' # Get your volume

unset GitHub GistHub AUTH
