#!/usr/bin/env bash

# set()
set -o interactive-comments -o vi -o braceexpand \
	-o hashall -o histexpand +o monitor

# shopt()
shopt -s autocd cdspell checkwinsize cmdhist \
	dirspell dotglob expand_aliases extglob extquote \
	force_fignore histappend hostcomplete \
	interactive_comments lithist no_empty_cmd_completion \
	progcomp progcomp_alias promptvars xpg_echo

# Use `clear-screen` instead for non-recursive clear
bind "\C-l":clear-display

# zsh(1) like menu completion
bind "TAB":menu-complete

# emacs(1) keys
bind "\C-a":beginning-of-line
bind "\C-e":end-of-line

# `colemak` vi(1)
bind -m vi "n":backward-char
bind -m vi "e":next-history
bind -m vi "i":previous-history
bind -m vi "o":forward-char

# Use `h` for insert mode
bind -m vi "h":vi-insertion-mode

PROMPT_PARSER() {
	# Colors
	local Red='\[\e[1;91m\]'
	local White='\[\e[1;97m\]'
	local Reset='\[\e[0m\]'

	# Status
	(($1 == 0)) || local Status=$1

	# PS1
	if ((UID == 0)); then
		if [[ -z $Status ]]; then
		 	PS1="${Red}->${Reset} "
		else
			PS1="${White}${Status}${Reset} ${Red}->${Reset} "
		fi
	else
		if [[ -z $Status ]]; then
			PS1="${White}->${Reset} "
		else
			PS1="${Red}${Status}${Reset} ${White}->${Reset} "
		fi
	fi

	# PS2
	PS2='   '
}

PROMPT_COMMAND='PROMPT_PARSER $?'

Make() { [[ -f $1 && -r $1 ]] && . $1 ;}

# Aliases
Make "$XDG_CONFIG_HOME/bash/aliases"

# Functions
Make "$XDG_CONFIG_HOME/bash/functions"

# Autostart
Make "$XDG_CONFIG_HOME/bash/autostart"

unset -f Make
