#!/usr/bin/env bash

# set()
set -o interactive-comments -o vi -o braceexpand \
	-o hashall -o histexpand +o monitor

# shopt()
shopt -s autocd cdspell checkwinsize cmdhist \
	dirspell dotglob expand_aliases extglob extquote \
	force_fignore histappend hostcomplete \
	interactive_comments lithist no_empty_cmd_completion \
	progcomp progcomp_alias promptvars xpg_echo

# Use `clear-screen` instead for non-recursive clear
bind "\C-l":clear-display

# zsh(1) like menu completion
bind "TAB":menu-complete

# emacs(1) keys
bind "\C-a":beginning-of-line
bind "\C-e":end-of-line

# `colemak` vi(1)
bind -m vi "n":backward-char
bind -m vi "e":next-history
bind -m vi "i":previous-history
bind -m vi "o":forward-char

# Use `h` for insert mode
bind -m vi "h":vi-insertion-mode

function PROMPT_PARSER {
	# Colors
	local Red='\e[1;91m'
	local White='\e[1;97m'
	local Reset='\e[0m'

	# Define colors for root and normal user
	if ((UID)); then
		local Main="$White"; local Fail="$Red"
	else
		local Main="$Red"; local Fail="$White"
	fi

	# Standard
	PS1= PS2='   '

	# Status
	(($1 == 0)) || local Status="$1 "
	((Status)) && PS1+="\[$Fail\]$Status\[$Reset\]"

	# Show current git branch
	if git rev-parse --is-inside-work-tree &>/dev/null; then
		read Branch < "$(git rev-parse --show-toplevel)/.git/HEAD"
		local Count=$((COLUMNS - ${#Status}))
		PS1+="\[$(tput sc; printf '%*s' $Count "(${Branch##*/})"; tput rc)\]"
		unset -v Branch
	fi

	# PS1
	PS1+="\[$Main\]->\[$Reset\] "

	# PS2
	if ((Status)); then
		local Count=0
		while ((Count != ${#Status})); do
			PS2+=' '; ((Count++))
		done
	fi
}

PROMPT_COMMAND='PROMPT_PARSER $?'

function Make { [[ -f $1 && -r $1 ]] && . $1 ;}

# Aliases
Make "$XDG_CONFIG_HOME/bash/aliases"

# Functions
Make "$XDG_CONFIG_HOME/bash/functions"

unset -f Make
