#!/usr/bin/env bash

Err() {
	printf '%s\n' "Err: $1" 1>&2
	return 1
}

up() {
	for ((Count = 10#${1:-1}; Count > 0; Count--)); {
		cd .. || break
	}
	unset -v Count
}

lspkg() { # [NAME] Inspired by TFL/LL
	for File in /var/cache/pacman/pkg/*; {
		if [[ $File != *'.sig' ]]; then
			printf '%s\n' "${File#/var/cache/pacman/pkg/}"
		fi
	}
}

build() {
	# Errors checking
	(( $# == 1 )) || { Err 'Need to specified a AUR...'; return 1 ;}

	# Set build dir
	local BuildDir="${TMPDIR:-/tmp}/build-$SRANDOM"

	# Copy AUR to build dir
	if cp -r "$1" "$BuildDir"; then
		# Build AUR
		{ cd "$BuildDir" && makepkg -sir ;} || Err "Build '$1' failed..."
	else
		Err "Copy '$1' to '$TMPDIR' failed..."
	fi

	# Clean
	cd "$OLDPWD" && rm -rf "$BuildDir"
}

log() {
	git --no-pager log --reverse --pretty=format:'%h: "%s"' "$@"
	printf '\n'
}

lq() { links https://lite.duckduckgo.com/lite/?q="$*" ;}
