#!/usr/bin/env bash

# \n = New line
# \w = $PWD
# \W = Current directory
# \h = $HOSTNAME
# \u = $USER
# \$ = Show `#` If root, otherwise `$`

PROMPT_PARSER() {

# Reset
local Reset='\[\e[0m\]'

# Normal
local Black='\[\e[30m\]';       local Red='\[\e[31m\]'
local Green='\[\e[32m\]';       local Yellow='\[\e[33m\]'
local Blue='\[\e[34m\]';        local Magenta='\[\e[35m\]'
local Cyan='\[\e[36m\]';        local White='\[\e[37m\]'

# Bold Normal
local B_Black='\[\e[1;30m\]';   local B_Red='\[\e[1;31m\]'
local B_Green='\[\e[1;32m\]';   local B_Yellow='\[\e[1;33m\]'
local B_Blue='\[\e[1;34m\]';    local B_Magenta='\[\e[1;35m\]'
local B_Cyan='\[\e[1;36m\]';    local B_White='\[\e[1;37m\]'

# Light
local L_Black='\[\e[90m\]';     local L_Red='\[\e[91m\]'
local L_Green='\[\e[92m\]';     local L_Yellow='\[\e[93m\]'
local L_Blue='\[\e[94m\]';      local L_Magenta='\[\e[95m\]'
local L_Cyan='\[\e[96m\]';      local L_White='\[\e[97m\]'

# Bold Light
local BL_Black='\[\e[1;90m\]';  local BL_Red='\[\e[1;91m\]'
local BL_Green='\[\e[1;92m\]';  local BL_Yellow='\[\e[1;93m\]'
local BL_Blue='\[\e[1;94m\]';   local BL_Magenta='\[\e[1;95m\]'
local BL_Cyan='\[\e[1;96m\]';   local BL_White='\[\e[1;97m\]'

local Status=$1
(( $Status == 0 )) && unset Status

### PS1
if (( $UID == 0 )); then
	if [ -z $Status ]; then
	 	PS1="${BL_Red}->${Reset} "
	else
		PS1="${BL_White}${Status}${Reset} ${BL_Red}->${Reset} "
	fi
else
	if [ -z $Status ]; then
		PS1="${BL_White}->${Reset} "
	else
		PS1="${BL_Red}${Status}${Reset} ${BL_White}->${Reset} "
	fi
fi

### PS2
PS2='   '

}

PROMPT_COMMAND='PROMPT_PARSER $?'
