#!/bin/sh

# Source autostart scripts
if [ -d $HOME/.config/X11/xinitrc.d ]; then

	for File in $HOME/.config/X11/xinitrc.d/?*.sh; do

		[ -x "$File" -a -r "$File" ] && . $File
	done
	unset File
fi

# Sessions manager
lxsession &

# I use `colemak`
setxkbmap us -variant colemak

# bspwm() doesn't set cursor by default
xsetroot -cursor_name left_ptr

# Unlike pulseaudio() you need to start pipewire() manually
pipewire &
pipewire-pulse &
pipewire-media-session &

# Even though I don't have screen tearing issues, I still love to have transpent
if read Type < /sys/class/dmi/id/product_name && [ "$Type" = VirtualBox ]; then
	# VSYNC in VM is unsupported
	picom --experimental-backends --no-vsync &
else
	picom --experimental-backends &
fi

unset Type

# feh() is more minimal than nitrogen()
feh --no-fehbg --bg-fill --randomize $HOME/pix/cWallpapers/ &

sxhkd & # sxhkd() is my prefered hotkeys daemon

exec bspwm # Your favorite WM/DE here!
