#!/bin/sh

export XDG_SESSION_TYPE=x11 GDK_BACKEND=x11

if test -d /etc/X11/xinit/xinitrc.d; then
	for file in /etc/X11/xinit/xinitrc.d/*.sh; do
		test -f "$file" -a -x "$file" && . "$file"
	done
	unset -v file
fi

xres=$XDG_CONFIG_HOME/X11/Xresources
if test -f "$xres" -a -r "$xres"; then
	xrdb "$xres"
fi
unset -v xres

setxkbmap us grammak_iso
xsetroot -cursor_name left_ptr

xset -dpms s off
redshift -PrO 4500
sxhkd &
dunst &
urxvtd -q -o -f

while :; do
	pacman -Qqu &&
	dunstify -u critical -r 86 "There's an update(s)..."
	sleep 60m
done &

feh --bg-fill --no-fehbg "$HOME"/Pictures/cWallpapers/Wallpaper_002.png &
picom -b

exec bspwm
