#!/usr/bin/env bash

# bash(1) completion for doas(1).
_doas() {

	local cur prev words cword split i
	_init_completion -s || return 0

	for (( i = 1; i <= cword; i++ )); {
		if [[ ${words[i]} != -* ]]; then
			local root_command=${words[i]}
			_command_offset "$i"
			return 0
		fi
		[[ ${words[i]} == -@(!(-*)[LnsCu]) ]] && (( i++ ))
	}

	case $prev in
		-!(-*)u)
			COMPREPLY=( $(compgen -u -- "$cur") )
			return 0 ;;

		-!(-*)C)
			_filedir ;;

		-!(-*)[Lns])
			return 0 ;;
	esac

	$split && return 0

	if [[ $cur == -* ]]; then
		COMPREPLY=( $(compgen -W '$(_parse_usage "$1")' -- "$cur") )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
		return 0
	fi

} && complete -F _doas doas
