#!/bin/sh

# Source autostart scripts
if [ -d $HOME/.config/X11/xinitrc.d ]; then

	# Your script is need to end with .sh
	for File in $HOME/.config/X11/xinitrc.d/?*.sh; do

		[ -x "$File" -a -r "$File" ] && . $File
	done
	unset File
fi

lxsession &

# My PP
setxkbmap us -variant colemak # I use `colemak` LOL
setxkbmap -option caps:backspace # Change Caps-Lock to Backspace (who use Caps-Lock anyways, lol)
xmodmap -e "clear Lock" # Apparently you need this for key repeat to works

xsetroot -cursor_name left_ptr # BSPWM doesn't set cursor by default

# Unlike PULSEAUDIO you need to start PIPEWIRE manually
pipewire &
pipewire-pulse &
pipewire-media-session &

# Even though I don't have Screen-tearing issues, I still love to have transpent
if [ "$(cat /sys/class/dmi/id/product_name)" = 'VirtualBox' ]; then
	picom --experimental-backends --no-vsync & # VSYNC in VM is unsupported
else
	picom --experimental-backends &
fi

feh --no-fehbg --bg-fill --randomize $HOME/Pictures/cWallpapers/ & # FEH is more minimal than NITROGEN

sxhkd & # SXHKD is my prefered hotkeys daemon

exec bspwm # Your favorite WM/DE here!
