#!/usr/bin/env bash

alias dl="cd $HOME/Downloads"
alias pic="cd $HOME/Pictures"
alias vid="cd $HOME/Videos"
alias doc="cd $HOME/Documents"
alias sg="cd $HOME/Music"
alias bin="cd $HOME/.local/bin"
alias src="cd $HOME/Src"
alias aur="cd $HOME/AUR"
alias cde="cd $HOME/Code"
