#!/usr/bin/env bash

#-------------------------------------------------Notes

# \n = newline
# \w = fullpath of current dir
# \W = current dir
# \h = hostname
# \u = username
# \$ = show '#' if root otherwise '$'


SetUp() {

#-------------------------------------------------`tput`

local T_Black='\[$(tput setaf 16)\]'; local T_Red='\[$(tput setaf 196)\]'
local T_Green='\[$(tput setaf 46)\]'; local T_Yellow='\[$(tput setaf 226)\]'
local T_Blue='\[$(tput setaf 21)\]'; local T_Magenta='\[$(tput setaf 201)\]'
local T_Cyan='\[$(tput setaf 51)\]'; local T_White='\[$(tput setaf 231)\]'
local T_Reset='\[$(tput sgr0)\]'

#-------------------------------------------------`ANSI escape code`

# Reset
local A_Reset='\[\e[0m\]'

# Normal
local A_Black='\[\e[30m\]'; local A_Red='\[\e[31m\]'
local A_Green='\[\e[32m\]'; local A_Yellow='\[\e[33m\]'
local A_Blue='\[\e[34m\]'; local A_Magenta='\[\e[35m\]'
local A_Cyan='\[\e[36m\]'; local A_White='\[\e[37m\]'

# Bold Normal
local BA_Black='\[\e[1;30m\]'; local BA_Red='\[\e[1;31m\]'
local BA_Green='\[\e[1;32m\]'; local BA_Yellow='\[\e[1;33m\]'
local BA_Blue='\[\e[1;34m\]'; local BA_Magenta='\[\e[1;35m\]'
local BA_Cyan='\[\e[1;36m\]'; local BA_White='\[\e[1;37m\]'

# Bright
local AB_Black='\[\e[90m\]'; local AB_Red='\[\e[91m\]'
local AB_Green='\[\e[92m\]'; local AB_Yellow='\[\e[93m\]'
local AB_Blue='\[\e[94m\]'; local AB_Magenta='\[\e[95m\]'
local AB_Cyan='\[\e[96m\]'; local AB_White='\[\e[97m\]'

# Bold Bright
local BAB_Black='\[\e[1;90m\]'; local BAB_Red='\[\e[1;91m\]'
local BAB_Green='\[\e[1;92m\]'; local BAB_Yellow='\[\e[1;93m\]'
local BAB_Blue='\[\e[1;94m\]'; local BAB_Magenta='\[\e[1;95m\]'
local BAB_Cyan='\[\e[1;96m\]'; local BAB_White='\[\e[1;97m\]'

#-------------------------------------------------Prompts

# PS1
PS1="${T_White}->"
PS1+="${T_Reset} "

# PS2
PS2='   '

}

SetUp && unset SetUp
