#!/bin/sh

# Colors
export TERM='xterm-256color'

# GNUPG
export GNUPGHOME="$HOME/.config/gnupg"

# `ps` in posix
export PS_PERSONALITY='posix'

## `ls`
# rs: Reset             no: Normal                  fi: File            di: Dir
# ln: SysLink           pi: Fifo                    so: Socket          bd: BlockDevice
# cd: CharDevice        mi: NonExistSysLink         or: OrphanSysLink   ex: Executable
# do: Door              su: SUID                    sg: SGID            st: StickyDir
# ow: OtherWritableDir  tw: StickyOtherWritableDir  ca: Cap             mh: MultiHardLink
export LS_COLORS='rs=0:no=0;37:pi=47;30:so=1;95:fi=1;97:di=1;91:st=41;1;97:tw=41;1;97:ln=1;96:or=4;1;96:mi=41;30:bd=4;32:cd=1;92:ex=1;93:su=4;1;97:sg=4;1;97'
