#!/bin/sh

export LESS='-FI --incsearch --no-histdups'
export LESSHISTFILE='/dev/null' # Same effect as LESSHISTFILE=''
export LESSHISTSIZE=0
export LESSSECURE=1 # Restricted `less`
export LESSKEYIN="$HOME/.config/less/config"
