#!/bin/sh

# Prefered programs
export EDITOR=vim
export VISUAL="$EDITOR"
export TERMINAL=alacritty
export PAGER=less
[ -n "$DISPLAY" ] && export BROWSER=firefox ||
	export BROWSER=links
export MANPAGER='less -R --use-color -Dd+r -Du+b' # Colorful man page
export SUDO_EDITOR=/usr/bin/rvim # I don't use `sudo`, but specify anyway
export DOAS_EDITOR="$SUDO_EDITOR" # This require by my `doasedit`
