#!/bin/sh

# Prefered programs.
export EDITOR='vim'
export VISUAL="$EDITOR"
export TERMINAL='alacritty'
export PAGER='less'
[ -n "$DISPLAY" ] && export BROWSER='firefox' ||
	export BROWSER='links' # Sometimes I walk around in tty

export SUDO_EDITOR='/usr/bin/rvim' # I don't use `sudo`, but specify anyway
export MANPAGER='less -R --use-color -Dd+r -Du+b' # Colorful manpage
