#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config pointer_modifier mod1
bspc config click_to_focus any

bspc config border_width 1
bspc config window_gap 10
bspc config normal_border_color '#0f0f0f'
bspc config focused_border_color '#2d2d2d'
bspc config presel_feedback false

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a 'Lxappearance' state=floating
bspc rule -a 'mpv' state=floating
