#!/bin/sh

#--------------------------------------------------------------Monitor Settings

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#---------------------------------------------------------------Window Settings

bspc config split_ratio 0.5
bspc config removal_adjustment true

bspc config borderless_monocle true
bspc config single_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus any
bspc config pointer_follows_focus true

#------------------------------------------------------------------------Colors

bspc config normal_border_color '#060606'
bspc config focused_border_color '#2d2d2d'
bspc config presel_feedback false

#--------------------------------------------------------------------Gaps Setup

#bspc config window_gap 10
#bspc config border_width 1

#bspc config top_monocle_padding 1
#bspc config right_monocle_padding 1
#bspc config bottom_monocle_padding 1
#bspc config left_monocle_padding 1

#-----------------------------------------------------------------Gapless Setup

bspc config gapless_monocle true
bspc config window_gap 0
bspc config border_width 0

#------------------------------------------------------------------Window Rules

bspc rule -a '*' state=floating
bspc rule -a 'URxvt' state=tiled
bspc rule -a 'firefoxdeveloperedition:*:Firefox Developer Edition' state=tiled
bspc rule -a 'firefoxdeveloperedition:*:Firefox Developer Edition (Private Browsing)' state=tiled
