#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config pointer_modifier mod1
bspc config click_to_focus any

bspc config border_width 1
bspc config window_gap 10
bspc config normal_border_color '#060606'
bspc config focused_border_color '#2d2d2d'
bspc config presel_feedback false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config top_monocle_padding 1
bspc config right_monocle_padding 1
bspc config bottom_monocle_padding 1
bspc config left_monocle_padding 1

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config single_monocle true

bspc rule -a '*' state=floating
bspc rule -a 'Alacritty' state=tiled
bspc rule -a 'firefox:*:Mozilla Firefox' state=tiled
bspc rule -a 'firefox:*:Mozilla Firefox (Private Browsing)' state=tiled
